#!/usr/bin/env python3

import logging, sys

# configure logging
# logging.basicConfig(format='%(levelname)s: %(message)s', stream=sys.stdout,
#                    level=logging.DEBUG if args.debug else logging.INFO)
logging.basicConfig(format='%(levelname)s: %(message)s', stream=sys.stdout,
                    level=logging.DEBUG)

from bass import parse_cmdline, create_project, build_site, http_server

# parse command line
args = parse_cmdline()

if args.create: # create new project
    create_project()
elif args.build: # build site in existing project
    build_site()
    # run server if requested
    if args.server:
        http_server('localhost', 8080)
else:
    logging.info('not building, not creating')
